title: OldmanChe's blog
author: OldmanChe
email: 619418101@qq.com
theme: minima
description: > # this means to ignore newlines until "baseurl:"
  This is my first blog, I'll record my study experience here.

# social links
twitter_username: no # DO NOT include the @ character, or else the build will fail!
github_username:  OldmanChe # DO NOT include the @ character, or else the build will fail!

show_excerpts: true # set to false to remove excerpts on the homepage
